# Generated by Django 3.1.dev20200318185912 on 2020-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birth_date', models.CharField(max_length=10, verbose_name='Date of Birth')),
                ('birth_place', models.CharField(max_length=50, verbose_name='Place of Birth')),
                ('profession', models.CharField(max_length=50, verbose_name='profession')),
                ('languages', models.CharField(max_length=50, verbose_name='Known Languages')),
                ('political_force', models.CharField(max_length=50, verbose_name='Political Force')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
