# Generated by Django 3.1.dev20200318185912 on 2020-09-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='NoName', max_length=10, verbose_name='Name'),
        ),
    ]
