# Generated by Django 3.1.dev20200318185912 on 2020-09-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restmember', '0002_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profession',
        ),
        migrations.CreateModel(
            name='profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(through='restmember.Member_profession', to='restmember.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member_profession',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restmember.Member'),
        ),
        migrations.AddField(
            model_name='member_profession',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restmember.profession'),
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(to='restmember.Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='member_profession',
            unique_together={('member', 'profession')},
        ),
    ]
